#!/usr/bin/env ruby
# frozen_string_literal: true

require 'active_support'
require 'semver'

versions = `git tag --list`.split("\n")
  .select { |item| item =~ %r{releases/\d+\.\d+\.\d+} }
  .map { |item| item.gsub('releases/', '') }
  .uniq
  .map { |item| item.split('.').map(&:to_i) }
  .map { |values| SemVer.new(values[0], values[1], values[2]) }
  .sort
  .map { |item| "#{item.major}.#{item.minor}.#{item.patch}" }

version = versions[-1]

if version.nil?
  puts '1.0.0'

  exit
end

split_version = version.split('.')
puts "#{split_version[0]}.#{split_version[1]}.#{split_version[2].to_i + 1}"
