services:
  mailserver:
    image: juanluisbaptiste/postfix:latest
    container_name: mailserver
    env_file:
      - ./.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
