name: Deploy API Website

on:
  # Manually trigger workflow
  workflow_dispatch:

  # When pushing a ref such as a branch or a tag
  push:
    branches:
      - "master"
      - "deploy-api-using-docker"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set-up-docker
        uses: docker-practice/actions-setup-docker@master

      - name: build-docker-image
        working-directory: ./api
        run: bash ../.github/scripts/api/build_docker_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

      - name: push-docker-image
        working-directory: ./api
        run: bash ../.github/scripts/api/push_docker_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install-docker-file
        run: bash ./.github/scripts/api/install_docker_file.sh
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"

      - name: build-local-danofer-image
        run: bash ./.github/scripts/api/build_danofer_image.sh
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
          SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

      - name: run-local-danofer-image
        run: bash ./.github/scripts/api/run_danofer_image.sh
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
