name: Deploy API Website

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: build-docker-image
        working-directory: ./api
        run: bash ../.github/scripts/api/build_docker_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: push-docker-image
        working-directory: ./api
        run: bash ../.github/scripts/api/push_docker_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: docker-practice/actions-setup-docker@master

      - name: build-local-danofer-image
        run: bash ../.github/scripts/api/build_danofer_image.sh
        working-directory: ./api
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

      - name: run-local-danofer-image
        run: bash ../.github/scripts/api/run_danofer_image.sh
        working-directory: ./api
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
