name: Configure NGINX

on:
  push:
    tags:
      - 'releases/*'

concurrency:
  group: deploy-configure-nginx
  cancel-in-progress: false

env:
  SERVER_RSA_PATH: 'rsa_ssh'
  OFER_TO_DOMAIN: 'ofer.to'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/create_server_rsa_key
        with:
          PRIVATE_RSA_KEY_PATH: ${{ env.SERVER_RSA_PATH }}
          PRIVATE_RSA_KEY_CONTENT: ${{ secrets.PROD_STATIC_SERVER_PRIVATE_KEY }}

      - name: Deploy TLS Certificate and Private Key
        run: |
          echo "${TLS_CERTIFICATE}" > ${TLS_CERTIFICATE_FILENAME}
          echo "${TLS_PRIVATE_KEY}" > ${TLS_PRIVATE_KEY_FILENAME}

          scp \
            -r \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i ${SERVER_RSA_PATH} \
            "${TLS_CERTIFICATE_FILENAME}" "${TLS_PRIVATE_KEY_FILENAME}" "root@${OFER_TO_DOMAIN}:${TLS_ENCRYPTION_PATH}"
        env:
          TLS_PRIVATE_KEY: ${{ secrets.PROD_TLS_CERTIFICATE_PRIVATE_KEY }}
          TLS_CERTIFICATE: ${{ secrets.PROD_TLS_CERTIFICATE }}
          TLS_PRIVATE_KEY_FILENAME: './star_ofer_to.crt'
          TLS_CERTIFICATE_FILENAME: './ofer_to.private.pem'
          TLS_ENCRYPTION_PATH: '/etc/letsencrypt/live/ofer.to'

      - name: Deploy NGINX Confs
        working-directory: ./nginx_confs
        run: |
          # scp \
          #   -o StrictHostKeyChecking=no \
          #   -o UserKnownHostsFile=/dev/null \
          #   -i ${SERVER_RSA_PATH} \
          #   ./sites-available/static.conf "root@${OFER_TO_DOMAIN}:/etc/nginx/sites-available"
          #
          # scp \
          #   -o StrictHostKeyChecking=no \
          #   -o UserKnownHostsFile=/dev/null \
          #   -i ${SERVER_RSA_PATH} \
          #   ./sites-available/api.conf "root@${OFER_TO_DOMAIN}:/etc/nginx/sites-available"
          #
          # scp \
          #   -o StrictHostKeyChecking=no \
          #   -o UserKnownHostsFile=/dev/null \
          #   -i ${SERVER_RSA_PATH} \
          #   ./dhparam.pem "root@${OFER_TO_DOMAIN}:/etc/nginx/dhparam.pem"

          scp \
            -r \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i ${SERVER_RSA_PATH} \
            ./nginx.conf ./dhparam.pem ./sites-available ./nginxconfig.io "root@${OFER_TO_DOMAIN}:/etc/nginx"
          #
          # scp ./sites-available/static.conf "root@${OFER_TO_DOMAIN}:/etc/nginx/sites-available"
          # scp ./sites-available/api.conf "root@${OFER_TO_DOMAIN}:/etc/nginx/sites-available"
          #
          # scp ./dhparam.pem "root@${OFER_TO_DOMAIN}:/etc/nginx/dhparam.pem"
          # scp ./nginx.conf "root@${OFER_TO_DOMAIN}:/etc/nginx/"
          # scp -r ./nginxconfig.io "root@${OFER_TO_DOMAIN}:/etc/nginx"
