name: Deploy Static Website

on:
  push:
    'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: Compile
        working-directory: ./static
        run: bash ../.github/scripts/static/compile.sh
        env:
          GOOGLE_TAG_ID: ${{ secrets.GOOGLE_TAG_ID }}

      - name: Deploy
        working-directory: ./static
        run: bash ../.github/scripts/static/deploy.sh
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
