name: Deploy Static Website

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/releases/')

    steps:
      - uses: actions/checkout@v2

      - name: install-node-14.17.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'

      - name: compile
        working-directory: ./static
        run: bash ../.github/scripts/static/compile.sh
        env:
          GOOGLE_TAG_ID: ${{ secrets.GOOGLE_TAG_ID }}

      - name: deploy
        working-directory: ./static
        run: bash ../.github/scripts/static/deploy.sh
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.STATIC_SERVER_PRIVATE_KEY }}
          SERVER_RSA: "./server_rsa"
