name: Deploy Static Website

on:
  push:
    tags:
      - 'releases/*'

env:
  HTML_STATIC_PATH: '/var/www/ofer_to'
  IP_ADDRESS: ${{ secrets.OFER_TO_IP_ADDRESS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: Compile
        working-directory: ./danofer
        run: |
          yarn && yarn build

      - name: Create Static Directory
        run: |
          # In case the directory does not exist
          set +e

          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i <(echo "${STATIC_SERVER_PRIVATE_KEY}") \
            "root@${IP_ADDRESS}" rm -rf ${HTML_STATIC_PATH}

          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i <(echo "${STATIC_SERVER_PRIVATE_KEY}") \
            "root@${IP_ADDRESS}" mkdir -p -- ${HTML_STATIC_PATH}

          set -e

      - name: Deploy
        working-directory: ./danofer/build
        run: |
          scp \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i <(echo "${STATIC_SERVER_PRIVATE_KEY}") \
              -r \
              index.html _app  \
              "root@${IP_ADDRESS}:${HTML_STATIC_PATH}"
