name: Deploy Static Website

on:
  push:
    # branches:
    #   - 'releases/*'

    tags:
      - 'releases/*'

env:
  SERVER_RSA: 'rsa_ssh'
  IP_ADDRESS: ${{ secrets.OFER_TO_IP_ADDRESS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create RSA file
        run: |
          echo "${STATIC_SERVER_PRIVATE_KEY}" > ${SERVER_RSA};

          # Remove its permissions
          chmod g-rwx ${SERVER_RSA};
          chmod o-rwx ${SERVER_RSA};
        env:
          STATIC_SERVER_PRIVATE_KEY: ${{ secrets.PROD_STATIC_SERVER_PRIVATE_KEY }}

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: Compile
        working-directory: ./danofer
        run: |
          yarn && yarn build

      - name: Deploy
        working-directory: ./danofer/build
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i "../../${SERVER_RSA}" \
            "root@${IP_ADDRESS}" mkdir -p -- /var/www/ofer_to

          # Deploy the static files to the remote server
          scp \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i "../../${SERVER_RSA}" \
              -r \
              index.html _app  \
              "root@${IP_ADDRESS}:/var/www/ofer_to"

          # Restart NGINX just in case
          # ssh \
          #     -o StrictHostKeyChecking=no \
          #     -o UserKnownHostsFile=/dev/null \
          #     -i "../../${SERVER_RSA}" \
          #     "root@${IP_ADDRESS}" \
          #     service nginx restart
